rdkcentral/ThunderInterfaces

interfaces/IBrowser.h

Below methods are changed to properties:
headers, useragent, languages, localstorageenabled and httpcookieacceptpolicy to properties. 
These methods are earlier used as get/set properties, so reverted back to properties.

Browser: interface doc updates + some of the methods changed to properties

---

interfaces/IExternal.h

The ICatalog::Resource() interface method is required for directly
getting the IExternal pointer to a give Pin ID, without having to listen
to ICatalog notifications.

IExternal: Add the legacy ICatalog::Resource() interface method

---

jsonrpc/DIALServer.json

These were implemented in the code, but not reflected in the .json file.

[IDIALServer] JSON-RPC: Include deprecated events in the documentation

---

interfaces/IPlayerInfo.h

Reason for change: Adding some more resoltuions
that are supported by comcast boxes. Missed to
add 2160p previously
Risks: None
Signed-off-by: Vinod Jacob <vinod_jacob@comcast.com>

XIONE-3049: Adding some more resolutions

---

jsonrpc/Messenger.json

Reason for change: Modify Messenger interface
Test Procedure: It builds
Risks: Low

RDK-29971: Thunder Messenger Restrictions

---

jsonrpc/WifiControl.json

I get incorrect type Core::JSON::DecUInt32 Signal; in https://github.com/rdkcentral/Thunder/tree/f53eec83fe4d09daff30f2bdbfa908e2d8dfa4f6
wifi signal will display incorrectly
Add these for safety

Fix wifi jsonrpc signal type and size

---

jsonrpc/Messenger.json

Reason for change: Add return code ERROR_ILLEGAL_STATE
for Messenger.1.create.
Test Procedure: See ticket
Risks: Low

RDK-29971: Add return codes

---

interfaces/IBrowser.h
interfaces/IDisplayInfo.h
interfaces/IVolumeControl.h
jsonrpc/WebKitBrowser.json

This updates the WebBrowser json rpc interface to be gererated (as much as possible) from the IWebBrowser interface while remaining backwards compatible with the already published json rpc interface (that was at that time generated from the json meta file instead of the C++ header file)
Also a first integration of the IApplication interface to WebKit was done but it is not yet complete and there will be no json rpc interface generated for it. 
Please note that these changes will (to some extend) break the current COM RPC interface and the json rpc interface generated from the IBrowser.h file.
The following pull request all belong to this and must be submitted together:
https://github.com/WebPlatformForEmbedded/ThunderNanoServicesRDK/pull/39 …

[WebKit] json rpc interface compatible

---

jsonrpc/Messenger.json

Reason for change: Introduce secure rooms based on thunder security.
Test Procedure: To create a secure room, pass "secure":true and
"acl":[....] to "join". To join a secure room, pass "secure":true and
no/empty acl. To specify which app can set acl use "acl" method
in thunder acl config.
Risks: Low

RDK-29971: Thunder Messenger security

---

interfaces/IBrowser.h
interfaces/Ids.h

IBrowserInterface allows to inject user's JavaScript and CSS code to
WebKit.

Add IBrowserResources interface

---

jsonrpc/WifiControl.json

- Differentiate between situations when there is no SSID and there is a wrong WPA method specified. ( https://github.com/rdkcentral/ThunderNanoServices/pull/455)
- Add error to communicate that plugin was not able to update configs on the disk (https://github.com/rdkcentral/ThunderNanoServices/pull/453)

[WiFi] Error codes

---

interfaces/IDolby.h

Reason for change: Comcast TV platforms let the user select "Auto" mode
which automatically detects the max capability of the connected AVR
and transcodes the incoming stream to match the max caps of the AVR
wherever possible.
Signed-off-by: Vinod Jacob vinod_jacob@comcast.com

RDKTV-9419: Playerinfo to include AUTO mode for sound settings

---

interfaces/IBrowser.h

The callbacks for 'headers' property are already registered in WebKitBrowser-plugin
in case of JSONRPC - WebKitBrowserJsonRpc.cpp

Don't generate 'headers' for JSONRPC from IBrowserResources interface

---

interfaces/IBrowser.h
interfaces/Ids.h

This change adds the IBrowserSecurity interface, which allows
to control security settings for secured connections and
the policy for handling mixed content.

ONEM-20501 Add IBrowserSecurity interface

---

interfaces/IPackager.h

Packager plugin should change the state of the downloaded plugin from "Unavailable" to "deactivated" on successful download of the RDM package

Packager plugin should change the state of the downloaded plugin from "Unavailable" to "deactivated"

---

interfaces/IBluetoothAudio.h

Microscopic fix to make the Time() method output only.

[IBluetoothAudio] Correct inout tag

---

definitions/Definitions.cpp
definitions/definitions.h
interfaces/IExternal.h

Move the static methods into an implementation file.

[UNLOADING] statics in header files and unloading does not go well.

---

interfaces/IBluetoothAudio.h

Adds two methods:
- Latency - means for a client app to adjust perceived latency, e.g. if a an assigned speaker has unusually high latency
- Delay - means to retrieve current time required for a frame to become audible (includes various factors on the host side, i.e. buffer fill level, compression time, serial baud rate, as well as the configured static sink latency with the Latency property), this is needed for precise A/V sync,

[IBluetoothAudio] Add latency and delay to the API

---

interfaces/IInputPin.h
interfaces/Ids.h

This commit implements a new ICatalog interface in IInputPin to add capability to query a Pin.
This is required to allow plugins to employ the IInputPin interface through json-rpc.

IInputPin: Add pin query interface

---

interfaces/ITimeZone.h
interfaces/Ids.h

Reason for change: ITimeZone interface for
get/set timezone (ex. in a file).
Test Procedure: Builds.
Risks: Low

RDKTV-11877: timezone interface

---

interfaces/IStore.h
interfaces/IStoreCache.h
interfaces/Ids.h

Reason for change: Store can be queried via interface.
Interface for notifications.
Test Procedure: Unit tests.
Risks: Low

RDK-35050: PersistentStore interface

---

interfaces/ITimeZone.h

If not added the json rpc documentation generation complains they are missing :)

[TimeZone] add json rpc documentation tags

---

interfaces/IContentDecryption.h
interfaces/Ids.h
jsonrpc/OCDM.json

Additional events exposed for OCDM - initialization flow with re-trying:
Example usage drmalreadyinitialized event:
registration:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drmalreadyinitialized", "id" : "OCDM" }}
event:
{"jsonrpc":"2.0","method":"OCDM.drmalreadyinitialized","params":{"drm":"PlayReady"}}
... will be received one time after initialization failed with CDMi::CDMi_RESULT::CDMi_BUSY_CANNOT_INITIALIZE, to make additional actions by external process (release drm resources).
Practical use case is returning DRM_E_BRCM_PLATFORM_ALREADY_INITIALIZED on Broadcom platform)
Example usage drminitializationstatus event:
registration:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drminitializationstatus", "id" : "OCDM" }} …

Onem 22983 api extension for drm initialization r3

---

interfaces/IContentDecryption.h
interfaces/Ids.h
jsonrpc/OCDM.json

Additional events exposed for OCDM - initialization flow with re-trying:
Example usage drmalreadyinitialized event:
registration:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drmalreadyinitialized", "id" : "OCDM" }}
event:
{"jsonrpc":"2.0","method":"OCDM.drmalreadyinitialized","params":{"drm":"PlayReady"}}
... will be received one time after initialization failed with CDMi::CDMi_RESULT::CDMi_BUSY_CANNOT_INITIALIZE, to make additional actions by external process (release drm resources).
Practical use case is returning DRM_E_BRCM_PLATFORM_ALREADY_INITIALIZED on Broadcom platform)
Example usage drminitializationstatus event:
registration:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drminitializationstatus", "id" : "OCDM" }} …

Onem 22983 api extension for drm initialization master

---

jsonrpc/OCDM.json

API to get list of active sessions. 
Example usage, lack of active sessions:
> { "jsonrpc": "2.0", "id": 1234567890, "method": "OCDM.1.sessions" }
< {"jsonrpc":"2.0","id":1234567890,"result":[]}
Example usage, single PlayReady session:
> { "jsonrpc": "2.0", "id": 1234567890, "method": "OCDM.1.sessions" }
< {"jsonrpc":"2.0","id":1234567890,"result":[{"drm":"PlayReady"}]}
It is safe to upstream that without providing implementation behaves in the following way:
> { "jsonrpc": "2.0", "id": 1234567890, "method": "OCDM.1.sessions" }
< {"jsonrpc":"2.0","id":1234567890,"error":{"code":-32601,"message":"Unknown method."}}
Implementation will be upstreamed after API update.
Reference for the implementation: 
https://github.com/LibertyGlobal/rdkservices/pull/75

ONEM-22979: OCDM JSONRPC: new ro sessions property and session data type

---

interfaces/IContentDecryption.h
interfaces/Ids.h
jsonrpc/OCDM.json

Additional events exposed for OCDM - initialization flow with re-trying:
Example usage drmalreadyinitialized event:
registration:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drmalreadyinitialized", "id" : "OCDM" }}
event:
{"jsonrpc":"2.0","method":"OCDM.drmalreadyinitialized","params":{"drm":"PlayReady"}}
... will be received one time after initialization failed with CDMi::CDMi_RESULT::CDMi_BUSY_CANNOT_INITIALIZE, to make additional actions by external process (release drm resources).
Practical use case is returning DRM_E_BRCM_PLATFORM_ALREADY_INITIALIZED on Broadcom platform)
Example usage drminitializationstatus event:
registration:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drminitializationstatus", "id" : "OCDM" }} …

Onem 22983 api extension for drm initialization r2

---

interfaces/Ids.h

To allow partial building always to succeed, put a way-of-working in place that makes the interface ID's
hard coded to the ID!
This request for partial builds came from LGI, using this way-of-working, we can comply to that request. Selecting a broader review audience to make us internally aware of this way of working. Also will discuss this in the internal team meetings we have.

[IDS] Partial building might lead to PS error.

---

interfaces/IPower.h

This commit adds more context to the callback function that notify the power state change events.
In addition to the new power state, the current power state and
the phase of transition (Before/After) is also included in parameters.
This change helps to send "Before" and "After" power state change notification.
v1(https://github.com/rdkcentral/ThunderInterfaces/pull/163) ->v2
- Modified StateChange() callback parameters to send out the values separately instead of using `struct PowerState`

RDKDEV-257: IPower: Update StateChange callback function to have more context

---

jsonrpc/DeviceInfo.json

Reason for change: New enum values for make, distributorid.
Remove "HDMI0" as default audio/video port.
Test Procedure: Test DeviceInfo for Sky platforms.
Risks: Low

DELIA-57105: DeviceInfo updates

---

CMakeLists.txt

Reason for change: Bumped libraries version to 2.1.11
Test Procedure: Build and verify.
Risks: Low
Signed-off-by:Zameerun Rasheed M S zexpen@gmail.com

RDK-37251: Thunder R2-v1.11 upgrade (Bug Fixes)

---

interfaces/IOCDM.h
interfaces/IPerformance.h
interfaces/IVoiceHandler.h

Following the changes to generators to differntiate between const pointer and pointer to const with https://github.com/rdkcentral/Thunder/pull/1048 some methods required disambiguation with `@in` tags.

Tag non const input parameters

---

interfaces/IBrowser.h
interfaces/Ids.h
jsonrpc/CookieJar.json

This adds API to 
- run JS code in web page main frame
- add/remove users scripts 
- needed support for "cloud" cookie jar

Extend IWebBrowser interface for XRE/X1 usecases

---

CMakeLists.txt
definitions/CMakeLists.txt
interfaces/CMakeLists.txt

Making the linking libraries PROVATE to avoid implementation leakage.

[CLEANUP] Removing dependencies to Tracing (if appplicable)

---

jsonrpc/AVInput.json

Reason for change:  As per generated header file from Json, adding Json types of parameters and responses.
Test Procedure: Steps mentioned in ticket
Risks: Low
Signed-off-by: Dhivya Ilangovan <dhivya.dilangovan@sky.uk>

RDKTV-19401: AVInput: Add generated classes instead of JsonObject

---

jsonrpc/DisplayInfo.json

This PR is to modify the DisplayInfo.json file to include a new property '**tvhdrtypes**'.
This property represents the HDR types supported by TV.

RDKDEV-438: DisplayInfo: Add new property for TV supported HDR types

---

interfaces/IDTV.h

Changed DTV StartServiceSearch functions to directly include tuning parameters, rather than using the separately created tuning parameter objects.

RDKDEV-677: Change to resolve deadlock and timeout when tuning using user defined tuning parameters

---

.github/workflows/Build ThunderInterfaces on Linux.yml

Referencing this action inside ThunderNanoServicesRDK breaks since the owner of this repo is different

[Actions] Repo owner can no longer be a parameter

---

interfaces/ITextToSpeech.h

Reason for change: User story RDK-42281
Risks: Low

Cherrypick RDK-42766:Changes on TTS thunder plugin for Supporting speechrate (#264) to R2

---

interfaces/ITextToSpeech.h

Reason for change: TTS thunder plugin missing "speechrate"
Risks: Low

DELIA-62843:TTS thunder plugin missing "speechrate" attribute

---

jsonrpc/LISA.json

No result is null in JSON-RPC. Empty object can be simply omitted.
These changes will not alter generated files, but upcoming update to JsonGenerator will prohibit use of empty objects in interface definitions.

[LISA] Remove redundant empty object

---

jsonrpc/DeviceInfo.json

There's contradicting information for some arrays using both "array" and "string" as type, confusing the generator.

[DeviceInfo] Correct documentation metadata

---

interfaces/ITextToSpeech.h

Reason for change: TTS thunder plugin missing "speechrate"
Risks: Low

(Cherry Pick R2)DELIA-62843:TTS thunder plugin missing "speechrate" attribute (#272)

---

interfaces/ITextToSpeech.h

Reason for change: TTS thunder plugin missing "speechrate"
Risks: Low

(Cherrypick R4)DELIA-62843:TTS thunder plugin missing "speechrate" attribute (#272)

---

interfaces/IDNSServer.h

Remove the redundancy of the label/designator as it is also part of the RECORD..

[IDNSServer] Make the interface explicit.

---

.github/workflows/Build ThunderInterfaces on Linux.yml

The last set of pull requests, now the new Actions will use workflows from our repos instead of my forks, which sadly couldn't have been done in one go.

[Actions] Using the already merged workflows instead of my forks

---

interfaces/IStore2.h
interfaces/Ids.h
jsonrpc/PersistentStore.json

Reason for change: Enhancements to PersistentStore plugin to support Scope, Time To Live.
Use of the RPC COM and JSON RPC interfaces.
Risks: None

RDK-45037 : Secure Storage Thunder Plugin

---

interfaces/ITextToSpeech.h

Reason for change: TTS plugin to support callsign based registeration
Risks: Low

ES1-631 - TTS thunder interface change

---

jsonrpc/DeviceInfo.json

Reason for change: return Sky_CP instead of Amlogic_Inc
Risks: None
Signed-off-by: ramkumar_prabaharan ramkumar_prabaharan@comcast.com
Change-Id: I9097043bf6229dc5497b2bb4602dde527362166e

RDKTV-31447 LlamaGlass make name shows Amlogic_Inc

---

interfaces/IStore2.h

Reason for change: Lowercase for consistency with previous json spec.
Risks: None

DELIA-66115: ScopeType enum case

---

interfaces/IStore2.h

Reason for change: Lowercase for consistency with previous json spec.
Risks: None

DELIA-66115: ScopeType enum case (#371)

---

interfaces/IPlayerInfo.h

Reason For Change: PlayerInfo service doesn't report AV1 codec though platform supports
Test procedure: Mentioned in the ticket RDKTV-35827
Risks: Low
Signed-off-by: vidhathri_joshi@comcast.com

RDKTV-35827: To list AV1 codec from PlayerInfo

---

interfaces/IContentProtection.h

Reason for change: align with the HLA
Risks: None

DELIA-68186 : Update interface to have closeSessionResponse parameter
