rdkcentral/ThunderInterfaces

interfaces/IApplication.h
=> [IApplication] Enum typoes fixed

jsonrpc/Messenger.json
=> RDK-29971: Thunder Messenger Restrictions

interfaces/IApplication.h, jsonrpc/DIALServer.json
Cosmetic changes to IApplication and IDIALServer yet still required for DIALServer alignment due to some generator quirks.
=> Development/for r2/dial upgrade

interfaces/IDRM.h
as implementations do in-place decryption.
=> [IDRM] Remove const for Decrypt Payload 

interfaces/IButler.h, interfaces/IOCDM.h, interfaces/Interfaces.vcxproj, interfaces/Interfaces.vcxproj.filters, jsonrpc/Butler.json, jsonrpc/IOControl.json
=> [Interfaces] Added IOControl and Butler

interfaces/IFocus.h, interfaces/Ids.h
Provide an option for the window manager to notify apps about focus change.
=> Add focus iface

interfaces/IInputPin.h, interfaces/Ids.h
It is based on following commit:
https://github.com/rdkcentral/ThunderInterfaces/commit/6da067eb50564685c79d8c8d5fc6d6e44bb292cd
=> Added IInputPin::ICatalog interface that allows to query IInputPin interface.

jsonrpc/LinearPlaybackControl.json
Added JSON interface description required for building LinearPlaybackControl plugin found in https://github.com/rdkcentral/rdkservices/pull/2482
See also https://jira.rdkcentral.com/jira/browse/RDKDEV-300
=> RDKDEV-300 : Add LinerPlaybackControl.json to ThunderInterfaces

jsonrpc/CASPlayerCommon.json, jsonrpc/UnifiedCASManagement.json, jsonrpc/UnifiedPlayer.json
Added support for new rdkservices
UnifiedPlayer
UnifiedCASManagement
=> RDKDEV-159: OCDM CAS Solution with new rdkservices

interfaces/CMakeLists.txt, interfaces/Interfaces.vcxproj, interfaces/Interfaces.vcxproj.filters
Make sure the interfaces directory is searched for "other" interfaces.
=> [WINDOWS] Add an additional interface file to the windows build.

interfaces/IContentDecryption.h, interfaces/IDRM.h
Enable passing the Subsample info to the DRM implementation
=> [OCDM] OCDM Enhancements

interfaces/ILISA.h, interfaces/Ids.h, jsonrpc/LISA.json
* possibility to lock/unlock an app
* locked apps cannot be uninstalled (and cannot be locked more than once at a time)
* operationStatus events contain more info:
- type,id,version of app
- operation (Installing,Uninstalling)
- status: new "Cancelled" status next to Success, Failed and Progress.
=> ONEM-22741 [dev] LISA locking mechanism

definitions/Definitions.cpp, interfaces/IRustBridge.h, interfaces/Ids.h, interfaces/Interfaces.vcxproj, interfaces/Interfaces.vcxproj.filters
Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>
=> RDKTV-37628 added RustBridge interface

NOTICE, interfaces/IPackageManager.h, interfaces/Ids.h
This is a copy of the ILISA interface, for now changes are only introduced to be able to generate the JSON RPC code from it, later on changes might be introduced to support other packagers
=> [PackMan] Introduction of IPackageManager interface

interfaces/ITextToSpeech.h, interfaces/Ids.h
Reason for change: upstream ITextToSpeech interface
Test Procedure: Mentioned in the ticket
Risks: Low
=> RDK-41683 Refine and upstream ITextToSpeech interface

interfaces/ITextToSpeech.h, interfaces/Ids.h
Reason for change: upstream ITextToSpeech interface
Test Procedure: Mentioned in the ticket
Risks: Low
=> Cherrypick RDK-41683 Refine and upstream ITextToSpeech interface (#253) to R2 branch

interfaces/ITextToSpeech.h
Reason for change: User story RDK-42281
Risks: Low
=> RDK-42766:Changes on TTS thunder plugin for Supporting speechrate

.github/workflows/Build ThunderInterfaces on Linux.yml
[DependsOn=ThunderInterfaces:development/correct-lisa]
=> [Actions] Adding a flag to build interfaces on a specific branch

.github/workflows/Build ThunderInterfaces on Linux.yml
=> [Actions] Treating warnings as errors

interfaces/IUserSettings.h, interfaces/Ids.h
Reason for change: Adding IUserSettings.h interface file.
Test Procedure: Build and verify
=> RDK-48604: New UserSettings Thunder Plugin

interfaces/IOCDM.h
The first part went in ProxyStubGenerator
https://github.com/rdkcentral/ThunderTools/pull/150
=> fix: This is second part fix for the OCDM crash

interfaces/IContentProtection.h
Reason for change: Update the thunder documentation for content protection service
Risks: None
=> DELIA-68254 : Update the interface for handling the specified errors

.github/workflows/Build ThunderInterfaces on Linux.yml, .github/workflows/Build ThunderInterfaces on MacOS.yml, .github/workflows/Build ThunderInterfaces on Windows.yml, .github/workflows/Linux build template.yml, .github/workflows/MacOS build template.yml
This is a fix for [this](https://github.com/rdkcentral/Thunder/security/code-scanning/15) code scanning alert
=> [Actions] Add permissions to all workflows
